import { EKEY_COLOR, EKEY_VARIATION, IKeyfield } from '@/types';


export function useKeyfieldHook(contents: string[] = [], multiple: boolean = true): Array<IKeyfield> {
    const list: Array<IKeyfield> = [
        {
            id: '1-1',
            keycodes: [27],
            location: 0,
            letters: ['Esc'],
            appendix: '',
            color: EKEY_COLOR.ORANGE,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '1-2',
            // keycodes: [49, 112],
            keycodes: [49],
            location: 0,
            letters: ['1', '!'],
            appendix: 'F1',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '1-3',
            // keycodes: [50, 113],
            keycodes: [50],
            location: 0,
            letters: ['2', '@'],
            appendix: 'F2',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '1-4',
            // keycodes: [51, 114],
            keycodes: [51],
            location: 0,
            letters: ['3', '#'],
            appendix: 'F3',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '1-5',
            // keycodes: [52, 115],
            keycodes: [52],
            location: 0,
            letters: ['4', '$'],
            appendix: 'F4',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '1-6',
            // keycodes: [53, 116],
            keycodes: [53],
            location: 0,
            letters: ['5', '%'],
            appendix: 'F5',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '1-7',
            // keycodes: [54, 117],
            keycodes: [54],
            location: 0,
            letters: ['6', '^'],
            appendix: 'F6',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '1-8',
            // keycodes: [55, 118],
            keycodes: [55],
            location: 0,
            letters: ['7', '&'],
            appendix: 'F7',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '1-9',
            // keycodes: [56, 119],
            keycodes: [56],
            location: 0,
            letters: ['8', '*'],
            appendix: 'F8',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '1-10',
            // keycodes: [57, 120],
            keycodes: [57],
            location: 0,
            letters: ['9', '('],
            appendix: 'F9',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '1-11',
            // keycodes: [48, 121],
            keycodes: [48],
            location: 0,
            letters: ['0', ')'],
            appendix: 'F10',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '1-12',
            // keycodes: [189, 122],
            keycodes: [189],
            location: 0,
            letters: ['-', '—'],
            appendix: 'F11',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '1-13',
            // keycodes: [187, 123],
            keycodes: [187],
            location: 0,
            letters: ['=', '+'],
            appendix: 'F12',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '1-14',
            keycodes: [8],
            location: 0,
            letters: ['←'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '2-1',
            keycodes: [9],
            location: 0,
            letters: ['Tab'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '2-2',
            keycodes: [81],
            location: 0,
            letters: ['Q'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '2-3',
            keycodes: [87],
            location: 0,
            letters: ['W'],
            appendix: '↑',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '2-4',
            keycodes: [69],
            location: 0,
            letters: ['E'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '2-5',
            keycodes: [82],
            location: 0,
            letters: ['R'],
            appendix: 'RGB',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '2-6',
            keycodes: [84],
            location: 0,
            letters: ['T'],
            appendix: 'RAT',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '2-7',
            keycodes: [89],
            location: 0,
            letters: ['Y'],
            appendix: 'BRT',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '2-8',
            keycodes: [85],
            location: 0,
            letters: ['U'],
            appendix: 'MOD',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '2-9',
            keycodes: [73],
            location: 0,
            letters: ['I'],
            appendix: '↑',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '2-10',
            keycodes: [79],
            location: 0,
            letters: ['O'],
            appendix: 'SL',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '2-11',
            keycodes: [80],
            location: 0,
            letters: ['P'],
            appendix: 'PB',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '2-12',
            keycodes: [219],
            location: 0,
            letters: ['[', '{'],
            appendix: 'HM',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '2-13',
            keycodes: [221],
            location: 0,
            letters: [']', '}'],
            appendix: 'END',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '2-14',
            keycodes: [220],
            location: 0,
            letters: ['\\', '¦'],
            appendix: 'PS',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '3-1',
            keycodes: [20],
            location: 0,
            letters: ['Caps'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '3-2',
            keycodes: [65],
            location: 0,
            letters: ['A'],
            appendix: '←',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '3-3',
            keycodes: [83],
            location: 0,
            letters: ['S'],
            appendix: '↓',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '3-4',
            keycodes: [68],
            location: 0,
            letters: ['D'],
            appendix: '→',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '3-5',
            keycodes: [70],
            location: 0,
            letters: ['F'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '3-6',
            keycodes: [71],
            location: 0,
            letters: ['G'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '3-7',
            keycodes: [72],
            location: 0,
            letters: ['H'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '3-8',
            keycodes: [74],
            location: 0,
            letters: ['J'],
            appendix: '←',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '3-9',
            keycodes: [75],
            location: 0,
            letters: ['K'],
            appendix: '↓',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '3-10',
            keycodes: [76],
            location: 0,
            letters: ['L'],
            appendix: '→',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '3-11',
            keycodes: [186],
            location: 0,
            letters: [';', ':'],
            appendix: 'PU',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '3-12',
            keycodes: [222],
            location: 0,
            letters: ['\'', '"'],
            appendix: 'PD',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '3-13',
            keycodes: [13],
            location: 0,
            letters: ['Enter'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '4-1',
            keycodes: [16],
            letters: ['Shit'],
            location: 1,
            appendix: '',
            color: EKEY_COLOR.GREEN,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '4-2',
            keycodes: [90],
            location: 0,
            letters: ['Z'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '4-3',
            keycodes: [88],
            location: 0,
            letters: ['X'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '4-4',
            keycodes: [67],
            location: 0,
            letters: ['C'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '4-5',
            keycodes: [86],
            location: 0,
            letters: ['V'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '4-6',
            keycodes: [66],
            location: 0,
            letters: ['B'],
            appendix: 'BT',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 2
        },
        {
            id: '4-7',
            keycodes: [78],
            location: 0,
            letters: ['N'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '4-8',
            keycodes: [77],
            location: 0,
            letters: ['M'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '4-9',
            keycodes: [188],
            location: 0,
            letters: [',', '<'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '4-10',
            keycodes: [190],
            location: 0,
            letters: ['.', '>'],
            appendix: 'INS',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '4-11',
            keycodes: [191],
            location: 0,
            letters: ['/', '?'],
            appendix: 'DEL',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 1
        },
        {
            id: '4-12',
            keycodes: [16],
            location: 2,
            letters: ['Shit'],
            appendix: '',
            color: EKEY_COLOR.GREEN,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '5-1',
            keycodes: [17],
            location: 1,
            letters: ['Ctrl'],
            appendix: '',
            color: EKEY_COLOR.ORANGE,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '5-2',
            keycodes: [91],
            location: 0,
            letters: ['Win'],
            appendix: 'LOCK',
            color: EKEY_COLOR.YELLOW,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '5-3',
            keycodes: [18],
            location: 1,
            letters: ['Alt'],
            appendix: '',
            color: EKEY_COLOR.BLUE,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '5-4',
            keycodes: [32],
            location: 0,
            letters: ['SPACE'],
            appendix: '',
            color: EKEY_COLOR.GRAY,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '5-5',
            keycodes: [18],
            location: 2,
            letters: ['Alt'],
            appendix: '',
            color: EKEY_COLOR.BLUE,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '5-6',
            keycodes: [],
            location: 0,
            letters: ['FN'],
            appendix: '',
            color: EKEY_COLOR.YELLOW,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '5-7',
            keycodes: [93],
            location: 0,
            letters: ['Anne'],
            appendix: '',
            color: EKEY_COLOR.YELLOW,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false,
            shit_position: 0
        },
        {
            id: '5-8',
            keycodes: [17],
            location: 2,
            letters: ['Ctrl'],
            appendix: '',
            color: EKEY_COLOR.ORANGE,
            press: false,
            multiple: true,
            anim: true,
            variation: EKEY_VARIATION.IDLE,
            shit: false, 
            shit_position: 0
        }
    ];

    let fields: IKeyfield[] = contents.map(c => {
        let fs = <IKeyfield>list.find(field => field.letters.some(s => s.toLowerCase() === c.toLowerCase()));
        let rs = { ...fs };
        rs.letters = [c];
        rs.multiple = multiple;
        rs.shit = RegExp(/^[A-Z]$/g).test(c) || fs.letters?.[1] === c ? true : false;
        return rs;
    });
    
    if (fields.length === 0) {
        fields = list.map(v => {
            let fs = { ...v };
            fs.multiple = multiple;
            return fs;
        });
    }

    return fields;
}